package com.isc.facebiometricservice.method1;

import com.isc.facebiometricservice.biometric.FaceMatcher;
import com.isc.facebiometricservice.biometric.ReferenceEmbeddingRepository;
import com.isc.facebiometricservice.config.BiometricProperties;
import com.isc.facebiometricservice.config.Method1Properties;
import com.isc.facebiometricservice.util.ModelPathResolver;
import org.opencv.core.*;
import org.opencv.imgproc.Imgproc;
import org.opencv.objdetect.FaceDetectorYN;
import ai.onnxruntime.*;
import org.springframework.stereotype.Service;
import java.nio.FloatBuffer;
import java.nio.file.Path;
import java.util.*;

@Service
public class Method1VerificationEngine {
 private final Method1Properties p; private final BiometricProperties biometric; private final FaceMatcher matcher; private final ReferenceEmbeddingRepository refs; private final FaceDetectorYN detector; private final OrtEnvironment env=OrtEnvironment.getEnvironment(); private final OrtSession recognition,liveness; private static final double[] TARGET={38.2946,51.6963,73.5318,51.5014,56.0252,71.7366};
 public Method1VerificationEngine(Method1Properties p,BiometricProperties biometric,FaceMatcher matcher,ReferenceEmbeddingRepository refs){this.p=p;this.biometric=biometric;this.matcher=matcher;this.refs=refs;try{Path detectorPath=ModelPathResolver.resolve(p.detectorModelPath());Path recognitionPath=ModelPathResolver.resolve(p.recognitionModelPath());Path livenessPath=ModelPathResolver.resolve(p.livenessModelPath());detector=FaceDetectorYN.create(detectorPath.toString(),"",new Size(320,320),.8f,.3f,5000);recognition=session(recognitionPath);liveness=session(livenessPath);}catch(Exception e){throw new IllegalStateException("Method 1 biometric models could not be initialized",e);}}
 private OrtSession session(Path path)throws Exception{return env.createSession(path.toString(),new OrtSession.SessionOptions());}
 public Outcome verify(VideoClipDecoder.DecodedClip clip,String referenceId){long start=System.nanoTime();List<Candidate> cands=new ArrayList<>();double liveSum=0;int liveCount=0;try{if(clip.durationSeconds()<p.minDurationSeconds())return out("INCONCLUSIVE",null,0,start,clip,0,"INVALID_VIDEO");if(clip.durationSeconds()>p.maxDurationSeconds())return out("INCONCLUSIVE",null,0,start,clip,0,"VIDEO_TOO_LONG");for(var f:clip.frames()){Detection d=detect(f.image());if(d.count==0)continue;if(d.count>p.maxFaces())return out("INCONCLUSIVE",null,0,start,clip,0,"MULTIPLE_FACES");if(d.box.w<p.minFaceSizePixels()||d.box.h<p.minFaceSizePixels())return out("INCONCLUSIVE",null,0,start,clip,0,"FACE_TOO_SMALL");Quality q=quality(f.image(),d.box);if(q.score<p.minQualityScore())continue;double ls=liveness(f.image(),d.box);liveSum+=ls;liveCount++;cands.add(new Candidate(f.image(),d,q));}if(cands.isEmpty())return out("INCONCLUSIVE",null,0,start,clip,0,"NO_FACE");double live=liveCount==0?0:liveSum/liveCount;if(p.livenessRequired()&&live<p.livenessThreshold())return out("INCONCLUSIVE",null,live,start,clip,0,"LIVENESS_FAILED");cands.sort(Comparator.comparingDouble((Candidate x)->x.quality.score).reversed());if(cands.size()>p.recognitionFrames())cands=new ArrayList<>(cands.subList(0,p.recognitionFrames()));var ref=refs.find(referenceId,biometric.modelId(),biometric.modelVersion());if(ref.isEmpty())return out("INCONCLUSIVE",null,live,start,clip,cands.size(),"REFERENCE_NOT_FOUND");List<Double> scores=new ArrayList<>();for(Candidate c:cands)scores.add(matcher.similarity(embedding(c.image,c.detection),ref.get().values()));double score=aggregate(scores,p.aggregation());return out(score>=biometric.threshold()?"MATCH":"NO_MATCH",score,live,start,clip,cands.size(),null);}finally{for(var f:clip.frames())f.image().release();}}
 private Outcome out(String r,Double s,double l,long st,VideoClipDecoder.DecodedClip clip,int n,String reason){return new Outcome(r,s,l,elapsed(st),clip.frames().size(),n,reason==null?List.of():List.of(reason));}
 private Detection detect(Mat image){detector.setInputSize(new Size(image.cols(),image.rows()));Mat faces=new Mat();try{detector.detect(image,faces);int n=faces.rows();if(n==0)return new Detection(0,null);int best=0;float score=-1;for(int i=0;i<n;i++){float[] row=new float[15];faces.get(i,0,row);if(row[14]>score){score=row[14];best=i;}}float[] row=new float[15];faces.get(best,0,row);return new Detection(n,new Box(row[0],row[1],row[2],row[3],row));}finally{faces.release();}}
 private Quality quality(Mat image,Box b){int x=Math.max(0,(int)b.x),y=Math.max(0,(int)b.y),w=Math.min(image.cols()-x,Math.max(1,(int)b.w)),h=Math.min(image.rows()-y,Math.max(1,(int)b.h));Mat crop=new Mat(image,new Rect(x,y,w,h)),gray=new Mat(),lap=new Mat();try{Imgproc.cvtColor(crop,gray,Imgproc.COLOR_BGR2GRAY);MatOfDouble mean=new MatOfDouble(),sd=new MatOfDouble();Core.meanStdDev(gray,mean,sd);Imgproc.Laplacian(gray,lap,CvType.CV_64F);MatOfDouble lm=new MatOfDouble(),ls=new MatOfDouble();Core.meanStdDev(lap,lm,ls);double blur=Math.min(1,ls.get(0,0)[0]*ls.get(0,0)[0]/400.0);double light=1-Math.min(1,Math.abs(mean.get(0,0)[0]-128)/128);double size=Math.min(1,Math.min(b.w/image.cols(),b.h/image.rows())/.18);return new Quality(.45*blur+.35*light+.20*size);}finally{crop.release();gray.release();lap.release();}}
 private double liveness(Mat image,Box b){Mat c=crop(image,b,80);try{float[] y=run(liveness,tensor(c,80),new long[]{1,3,80,80});double[]q=softmax(y);return q.length>1?q[1]:0;}finally{c.release();}}
 private float[] embedding(Mat image,Detection d){Mat a=align(image,d.box.values);try{return normalize(run(recognition,tensor(a,112),new long[]{1,3,112,112}));}finally{a.release();}}
 private Mat align(Mat f,float[]v){MatOfPoint2f s=new MatOfPoint2f(new Point(v[4],v[5]),new Point(v[6],v[7]),new Point(v[8],v[9])),t=new MatOfPoint2f(new Point(TARGET[0],TARGET[1]),new Point(TARGET[2],TARGET[3]),new Point(TARGET[4],TARGET[5]));Mat m=Imgproc.getAffineTransform(s,t),o=new Mat();Imgproc.warpAffine(f,o,m,new Size(112,112));s.release();t.release();m.release();return o;}
 private Mat crop(Mat image,Box b,int size){int x=Math.max(0,(int)b.x),y=Math.max(0,(int)b.y),w=Math.min(image.cols()-x,Math.max(1,(int)b.w)),h=Math.min(image.rows()-y,Math.max(1,(int)b.h));Mat c=new Mat(image,new Rect(x,y,w,h)),o=new Mat();Imgproc.resize(c,o,new Size(size,size));c.release();return o;}
 private float[] tensor(Mat image,int size){Mat f=new Mat();image.convertTo(f,CvType.CV_32FC3);float[]hwc=new float[size*size*3];f.get(0,0,hwc);float[]chw=new float[hwc.length];int plane=size*size;for(int y=0;y<size;y++)for(int x=0;x<size;x++){int a=(y*size+x)*3,q=y*size+x;chw[q]=(hwc[a+2]-127.5f)/127.5f;chw[plane+q]=(hwc[a+1]-127.5f)/127.5f;chw[2*plane+q]=(hwc[a]-127.5f)/127.5f;}f.release();return chw;}
 private float[]run(OrtSession s,float[]x,long[]shape){try(OnnxTensor t=OnnxTensor.createTensor(env,FloatBuffer.wrap(x),shape);OrtSession.Result r=s.run(Map.of(s.getInputNames().iterator().next(),t))){Object v=r.get(0).getValue();return v instanceof float[][]a?a[0]:(float[])v;}catch(Exception e){throw new IllegalStateException("MODEL_ERROR",e);}}
 private float[]normalize(float[]x){double n=0;for(float v:x)n+=v*v;n=Math.sqrt(n);if(n==0)throw new IllegalArgumentException("MODEL_ERROR");float[]o=new float[x.length];for(int i=0;i<x.length;i++)o[i]=(float)(x[i]/n);return o;}
 private double[]softmax(float[]x){double m=-Double.MAX_VALUE;for(float v:x)m=Math.max(m,v);double sum=0;double[]o=new double[x.length];for(int i=0;i<x.length;i++){o[i]=Math.exp(x[i]-m);sum+=o[i];}for(int i=0;i<o.length;i++)o[i]/=sum;return o;}
 private double aggregate(List<Double>s,String mode){if(s.isEmpty())return 0;if("MAX".equalsIgnoreCase(mode))return Collections.max(s);if("MEDIAN".equalsIgnoreCase(mode)){var x=new ArrayList<>(s);Collections.sort(x);return x.get(x.size()/2);}return s.stream().mapToDouble(Double::doubleValue).average().orElse(0);}
 private long elapsed(long n){return(System.nanoTime()-n)/1_000_000;} public record Outcome(String result,Double similarity,Double livenessScore,long processingMs,int decodedFrames,int recognitionFrames,List<String> reasons){} private record Detection(int count,Box box){} private record Box(float x,float y,float w,float h,float[] values){} private record Quality(double score){} private record Candidate(Mat image,Detection detection,Quality quality){}
}
