package com.isc.facebiometricservice.service;

import com.isc.facebiometricservice.api.VerificationRequest;
import com.isc.facebiometricservice.api.VerificationResponse;
import com.isc.facebiometricservice.api.VerificationStatus;
import com.isc.facebiometricservice.biometric.FaceMatcher;
import com.isc.facebiometricservice.biometric.ReferenceEmbeddingRepository;
import com.isc.facebiometricservice.config.BiometricProperties;
import com.isc.facebiometricservice.domain.FaceEmbedding;
import com.isc.facebiometricservice.model.FaceModelRegistry;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class BiometricVerificationService {
    private final ReferenceEmbeddingRepository repository;
    private final FaceMatcher matcher;
    private final BiometricProperties properties;
    private final FaceModelRegistry modelRegistry;

    public BiometricVerificationService(ReferenceEmbeddingRepository repository,
                                        FaceMatcher matcher,
                                        BiometricProperties properties,
                                        FaceModelRegistry modelRegistry) {
        this.repository = repository;
        this.matcher = matcher;
        this.properties = properties;
        this.modelRegistry = modelRegistry;
    }

    public VerificationResponse verify(VerificationRequest request) {
        if (request == null || request.capture() == null) {
            return invalid(null, null, "EMBEDDING", "CAPTURE_REQUIRED",
                    "A biometric capture is required.", null);
        }
        if (!"EMBEDDING".equalsIgnoreCase(request.capture().type())) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "CAPTURE_TYPE_NOT_SUPPORTED", "The requested capture type is not supported.", request.model());
        }

        var model = request.model();
        if (model == null || isBlank(model.modelId()) || isBlank(model.modelVersion()) || model.dimension() == null) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "MODEL_METADATA_REQUIRED",
                    "modelId, modelVersion, and dimension are required for embedding verification.",
                    model);
        }

        var descriptor = modelRegistry.find(model.modelId(), model.modelVersion());
        if (descriptor.isEmpty()) {
            return modelMismatch(request, model,
                    "The supplied embedding was generated by an unsupported biometric model.",
                    "MODEL_MISMATCH");
        }

        if (model.dimension() != descriptor.get().dimension()) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "EMBEDDING_DIMENSION_MISMATCH",
                    "The embedding dimension does not match the registered biometric model.",
                    model);
        }

        if (request.capture().embedding() == null
                || request.capture().embedding().size() != descriptor.get().dimension()) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "EMBEDDING_DIMENSION_MISMATCH",
                    "The embedding dimension does not match the registered biometric model.",
                    model);
        }

        boolean normalized = Boolean.TRUE.equals(request.capture().normalized());
        if (descriptor.get().normalized() && !normalized) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "NORMALIZED_EMBEDDING_REQUIRED",
                    "A normalized embedding is required for the selected biometric model.",
                    model);
        }

        float[] values = toArray(request.capture().embedding());
        if (containsNonFinite(values)) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "INVALID_EMBEDDING",
                    "The embedding contains non-finite values.",
                    model);
        }

        if (descriptor.get().normalized() && !isL2Normalized(values)) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "INVALID_EMBEDDING",
                    "The embedding is marked normalized but its vector norm is outside the accepted range.",
                    model);
        }

        var reference = repository.find(request.referenceId(), descriptor.get().modelId(), descriptor.get().modelVersion());
        if (reference.isEmpty()) {
            var anyReference = repository.findByReferenceId(request.referenceId());
            if (anyReference.isPresent()) {
                return modelMismatch(request, model,
                        "The reference exists, but its enrolled biometric model is incompatible with the supplied embedding.",
                        "MODEL_MISMATCH");
            }
            return outcome(request.requestId(), request.referenceId(), "EMBEDDING",
                    VerificationStatus.INCONCLUSIVE, "REFERENCE_NOT_FOUND",
                    "No biometric reference embedding is enrolled for this reference.",
                    null, properties.threshold(), null, null,
                    metadata(descriptor.get()), List.of("REFERENCE_NOT_FOUND"));
        }

        FaceEmbedding ref = reference.get();
        if (!descriptor.get().modelId().equals(ref.modelId())
                || !descriptor.get().modelVersion().equals(ref.modelVersion())
                || descriptor.get().dimension() != ref.dimension()) {
            return modelMismatch(request, model,
                    "The enrolled reference metadata does not match the registered biometric model.",
                    "MODEL_MISMATCH");
        }

        try {
            double similarity = matcher.similarity(values, ref.values());
            VerificationStatus result = similarity >= properties.threshold()
                    ? VerificationStatus.MATCH
                    : VerificationStatus.NO_MATCH;
            String code = result == VerificationStatus.MATCH ? "MATCH" : "SIMILARITY_BELOW_THRESHOLD";
            String message = result == VerificationStatus.MATCH
                    ? "Biometric verification matched the enrolled reference."
                    : "Biometric verification completed, but similarity is below the configured threshold.";

            return outcome(request.requestId(), request.referenceId(), "EMBEDDING",
                    result, code, message, similarity, properties.threshold(), null, null,
                    metadata(descriptor.get()), List.of(code));
        } catch (IllegalArgumentException ex) {
            return invalid(request.requestId(), request.referenceId(), "EMBEDDING",
                    "INVALID_EMBEDDING", "The supplied embedding could not be verified.", model);
        }
    }

    private VerificationResponse modelMismatch(VerificationRequest request,
                                                VerificationRequest.ModelMetadata model,
                                                String message,
                                                String code) {
        return outcome(request.requestId(), request.referenceId(), "EMBEDDING",
                VerificationStatus.INVALID_REQUEST, code, message,
                null, null, null, null,
                model == null ? null : new VerificationResponse.ModelMetadata(
                        model.modelId(), model.modelVersion(),
                        model.dimension() == null ? properties.dimension() : model.dimension(),
                        properties.algorithm()),
                List.of(code));
    }

    private VerificationResponse invalid(String requestId, String referenceId, String method,
                                         String code, String message,
                                         VerificationRequest.ModelMetadata model) {
        VerificationResponse.ModelMetadata responseModel = model == null
                ? new VerificationResponse.ModelMetadata(
                properties.modelId(), properties.modelVersion(),
                properties.dimension(), properties.algorithm())
                : new VerificationResponse.ModelMetadata(
                model.modelId(), model.modelVersion(),
                model.dimension() == null ? properties.dimension() : model.dimension(),
                properties.algorithm());

        return outcome(requestId, referenceId, method, VerificationStatus.INVALID_REQUEST,
                code, message, null, properties.threshold(), null, null,
                responseModel, List.of(code));
    }

    private VerificationResponse outcome(String requestId, String referenceId, String method,
                                         VerificationStatus result, String code, String message,
                                         Double similarity, Double threshold,
                                         VerificationResponse.QualityLiveness quality,
                                         VerificationResponse.Metrics metrics,
                                         VerificationResponse.ModelMetadata model,
                                         List<String> reasons) {
        int httpStatus;
        if ("MODEL_MISMATCH".equals(code)) {
            httpStatus = 409;
        } else if (result == VerificationStatus.INVALID_REQUEST) {
            httpStatus = 400;
        } else if (result == VerificationStatus.PROCESSING_ERROR) {
            httpStatus = 500;
        } else {
            httpStatus = 200;
        }

        return new VerificationResponse(
                requestId,
                referenceId,
                method,
                result,
                code,
                message,
                httpStatus,
                similarity,
                threshold == null ? properties.threshold() : threshold,
                model == null
                        ? new VerificationResponse.ModelMetadata(
                        properties.modelId(), properties.modelVersion(),
                        properties.dimension(), properties.algorithm())
                        : model,
                quality == null ? new VerificationResponse.QualityLiveness(null, null, null) : quality,
                metrics == null ? new VerificationResponse.Metrics(0L, null, null, null) : metrics,
                reasons == null ? List.of() : reasons);
    }

    private VerificationResponse.ModelMetadata metadata(FaceModelRegistry.FaceModelDescriptor descriptor) {
        return new VerificationResponse.ModelMetadata(
                descriptor.modelId(),
                descriptor.modelVersion(),
                descriptor.dimension(),
                descriptor.algorithm());
    }

    private static float[] toArray(List<Float> values) {
        float[] result = new float[values.size()];
        for (int i = 0; i < values.size(); i++) {
            result[i] = values.get(i);
        }
        return result;
    }

    private static boolean containsNonFinite(float[] values) {
        for (float value : values) {
            if (!Float.isFinite(value)) {
                return true;
            }
        }
        return false;
    }

    private static boolean isL2Normalized(float[] values) {
        double sum = 0.0;
        for (float value : values) {
            sum += (double) value * value;
        }
        double norm = Math.sqrt(sum);
        return Double.isFinite(norm) && Math.abs(norm - 1.0) <= 0.02;
    }

    private static boolean isBlank(String value) {
        return value == null || value.isBlank();
    }
}
