package com.isc.faceclientsimulator.api;

import com.isc.faceclientsimulator.domain.FaceEmbedding;
import com.isc.faceclientsimulator.service.BiometricFrameProcessor;
import com.isc.faceclientsimulator.client.BiometricServerClient;
import com.isc.faceclientsimulator.client.HybridVerificationServerClient;
import com.isc.faceclientsimulator.client.ServerVerifyResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.MediaType;
import org.springframework.util.StringUtils;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

@RestController
@RequestMapping("/api/v1/simulator")
public class SimulatorController {
    private static final Logger log=LoggerFactory.getLogger(SimulatorController.class);
    private final BiometricFrameProcessor processor; private final BiometricServerClient serverClient; private final HybridVerificationServerClient hybridClient;
    private final ConcurrentHashMap<String,Boolean> sessions=new ConcurrentHashMap<>();
    public SimulatorController(BiometricFrameProcessor processor,BiometricServerClient serverClient,HybridVerificationServerClient hybridClient){this.processor=processor;this.serverClient=serverClient;this.hybridClient=hybridClient;}
    @GetMapping("/models") public ModelsResponse models(){log.info("[SIM][MODELS] Model information requested");return new ModelsResponse("YuNet","MobileFaceNet w600k_mbf (client); ArcFace w600k_r50 (server modes)","MiniFASNetV2 + temporal",512);}
    @GetMapping("/server-status") public ServerStatusResponse serverStatus(){log.info("[SIM][HEALTH] Server status requested");return serverClient.health();}
    @PostMapping("/sessions") public SessionResponse createSession(){String id=UUID.randomUUID().toString();sessions.put(id,true);log.info("[SIM][SESSION_CREATED] sessionId={}",id);return new SessionResponse(id);}
    @DeleteMapping("/sessions/{sessionId}") public void delete(@PathVariable String sessionId){sessions.remove(sessionId);processor.resetSession(sessionId);log.info("[SIM][SESSION_DELETED] sessionId={}",sessionId);}
    @PostMapping(value="/frames",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Object frame(@RequestParam String sessionId,@RequestPart("image") MultipartFile image)throws Exception{requireSession(sessionId);requireImage(image);log.debug("[SIM][FRAME_START] sessionId={} bytes={}",sessionId,image.getSize());var result=processor.analyze(sessionId,image.getBytes());log.info("[SIM][FRAME_RESULT] sessionId={} faceDetected={} faceCount={} liveness={} live={} quality={} acceptedFrames={}",sessionId,result.detection().faceDetected(),result.detection().faceCount(),result.liveness().status(),result.liveness().frameLooksLive(),result.qualityScore(),result.liveness().acceptedFrames());return result;}
    @PostMapping(value="/embedding",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public FaceEmbeddingResponse embedding(@RequestPart("image") MultipartFile image)throws Exception{requireImage(image);FaceEmbedding e=processor.generateEmbedding(image.getBytes());log.info("[SIM][EMBEDDING] model={} version={} dimension={}",e.modelId(),e.modelVersion(),e.dimension());return new FaceEmbeddingResponse(e.modelId(),e.modelVersion(),e.dimension(),e.normalized(),e.values());}
    @PostMapping(value="/enroll",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ServerVerifyResponse enroll(@RequestParam String sessionId,@RequestParam String userId,@RequestPart("image") MultipartFile image)throws Exception{requireSession(sessionId);requireImage(image);log.info("[SIM][ENROLL_START] user={} session={}",userId,sessionId);var analysis=processor.analyze(sessionId,image.getBytes());if(!analysis.liveness().frameLooksLive())throw new IllegalStateException("Liveness has not passed: "+analysis.liveness().status());FaceEmbedding e=processor.generateEmbedding(image.getBytes());log.info("[SIM][ENROLL_SERVER] user={} model={} dimension={}",userId,e.modelId(),e.dimension());return serverClient.enroll(userId,e);}
    @PostMapping(value="/verify",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ServerVerifyResponse verify(@RequestParam String sessionId,@RequestParam String userId,@RequestPart("image") MultipartFile image)throws Exception{requireSession(sessionId);requireImage(image);log.info("[SIM][VERIFY_START] user={} session={}",userId,sessionId);var analysis=processor.analyze(sessionId,image.getBytes());if(!analysis.liveness().frameLooksLive())throw new IllegalStateException("Liveness has not passed: "+analysis.liveness().status());FaceEmbedding e=processor.generateEmbedding(image.getBytes());log.info("[SIM][VERIFY_SERVER] user={} model={} dimension={}",userId,e.modelId(),e.dimension());return serverClient.verify(userId,e);}
    @PostMapping(value="/client-embedding",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public FaceEmbeddingResponse clientEmbedding(@RequestPart("image") MultipartFile image)throws Exception{requireImage(image);FaceEmbedding e=processor.generateClientEmbedding(image.getBytes());log.info("[SIM][CLIENT_EMBEDDING] model={} version={} dimension={}",e.modelId(),e.modelVersion(),e.dimension());return new FaceEmbeddingResponse(e.modelId(),e.modelVersion(),e.dimension(),e.normalized(),e.values());}
    @PostMapping(value="/client-verify",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ServerVerifyResponse clientVerify(@RequestParam String sessionId,@RequestParam String userId,@RequestPart("image") MultipartFile image)throws Exception{requireSession(sessionId);requireImage(image);log.info("[SIM][CLIENT_VERIFY_START] user={} session={}",userId,sessionId);var a=processor.analyze(sessionId,image.getBytes());if(!a.liveness().frameLooksLive())throw new IllegalStateException("Temporal liveness has not passed: "+a.liveness().status());FaceEmbedding e=processor.generateClientEmbedding(image.getBytes());return serverClient.verifyClient(userId,e);}
    @PostMapping(value="/client-enroll",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ServerVerifyResponse clientEnroll(@RequestParam String sessionId,@RequestParam String userId,@RequestPart("image") MultipartFile image)throws Exception{requireSession(sessionId);requireImage(image);log.info("[SIM][CLIENT_ENROLL_START] user={} session={}",userId,sessionId);var a=processor.analyze(sessionId,image.getBytes());if(!a.liveness().frameLooksLive())throw new IllegalStateException("Temporal liveness has not passed: "+a.liveness().status());FaceEmbedding e=processor.generateClientEmbedding(image.getBytes());return serverClient.enrollClient(userId,e);}
    @PostMapping("/hybrid/sessions") public Object hybridSession(@RequestParam String referenceId){log.info("[SIM][HYBRID_SESSION_START] referenceId={}",referenceId);return hybridClient.createSession(referenceId);}
    @PostMapping(value="/hybrid/verify",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public Object hybridVerify(@RequestParam String sessionId,@RequestParam String referenceId,@RequestPart("image") MultipartFile image)throws Exception{requireImage(image);log.info("[SIM][HYBRID_UPLOAD_START] sessionId={} referenceId={} bytes={}",sessionId,referenceId,image.getSize());Object result=hybridClient.verify(sessionId,referenceId,image.getBytes());log.info("[SIM][HYBRID_SERVER_RESULT] sessionId={} referenceId={} result={}",sessionId,referenceId,result);return result;}
    private void requireSession(String id){if(!sessions.containsKey(id)){log.warn("[SIM][SESSION_INVALID] sessionId={}",id);throw new IllegalArgumentException("Unknown session: "+id);}}
    private void requireImage(MultipartFile file){if(file==null||file.isEmpty())throw new IllegalArgumentException("Image is required");if(!StringUtils.hasText(file.getContentType())||!file.getContentType().startsWith("image/"))throw new IllegalArgumentException("Only image uploads are accepted");}
    public record SessionResponse(String sessionId){} public record ModelsResponse(String detector,String recognition,String liveness,int embeddingDimension){} public record FaceEmbeddingResponse(String modelId,String modelVersion,int dimension,boolean normalized,float[] embedding){} public record ServerStatusResponse(boolean reachable,String status,String message){}
}