package com.isc.facebiometricservice.api;

import com.isc.facebiometricservice.videoverification.VideoVerificationEngine;
import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.http.MediaType;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
import java.time.Duration;import java.time.Instant;import java.util.List;import java.util.Map;import java.util.UUID;import java.util.concurrent.ConcurrentHashMap;import java.util.concurrent.atomic.AtomicBoolean;

@RestController
@RequestMapping("/api/v1/biometric/hybrid-verification")
public class HybridBestFrameVerificationController {
 private static final Logger log=LoggerFactory.getLogger(HybridBestFrameVerificationController.class); private static final Duration SESSION_TTL=Duration.ofMinutes(2); private static final long MAX_IMAGE_BYTES=8L*1024*1024;
 private final VideoVerificationEngine engine; private final Map<String,Session> sessions=new ConcurrentHashMap<>();
 public HybridBestFrameVerificationController(VideoVerificationEngine engine){this.engine=engine;log.info("[HYBRID][INIT] Hybrid best-frame verification controller initialized; sessionTtl={}s maxImageBytes={}",SESSION_TTL.toSeconds(),MAX_IMAGE_BYTES);}
 @PostMapping("/sessions") public SessionResponse createSession(@RequestParam String referenceId){if(referenceId==null||referenceId.isBlank())throw new IllegalArgumentException("referenceId is required");String id=UUID.randomUUID().toString();Instant exp=Instant.now().plus(SESSION_TTL);sessions.put(id,new Session(id,referenceId,exp,false));log.info("[HYBRID][SESSION_CREATED] sessionId={} referenceId={} expiresAt={}",id,referenceId,exp);return new SessionResponse(id,referenceId,exp);}
 @PostMapping(value="/verify",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public HybridVerificationResponse verify(@RequestParam String sessionId,@RequestParam String referenceId,@RequestPart("image") MultipartFile image){String requestId=UUID.randomUUID().toString();log.info("[HYBRID][VERIFY_RECEIVED] requestId={} sessionId={} referenceId={} bytes={} contentType={}",requestId,sessionId,referenceId,image==null?0:image.getSize(),image==null?null:image.getContentType());Session s=sessions.get(sessionId);if(s==null){log.warn("[HYBRID][REJECTED] requestId={} reason=SESSION_NOT_FOUND",requestId);return invalid(requestId,referenceId,"SESSION_NOT_FOUND");}if(s.expiresAt().isBefore(Instant.now())){sessions.remove(sessionId);log.warn("[HYBRID][REJECTED] requestId={} reason=SESSION_EXPIRED",requestId);return invalid(requestId,referenceId,"SESSION_EXPIRED");}if(!s.referenceId().equals(referenceId)){log.warn("[HYBRID][REJECTED] requestId={} reason=REFERENCE_ID_MISMATCH expected={} received={}",requestId,s.referenceId(),referenceId);return invalid(requestId,referenceId,"REFERENCE_ID_MISMATCH");}if(image==null||image.isEmpty())return invalid(requestId,referenceId,"INVALID_IMAGE");if(image.getSize()>MAX_IMAGE_BYTES)return invalid(requestId,referenceId,"IMAGE_TOO_LARGE");String ct=image.getContentType();if(ct==null||!ct.startsWith("image/"))return invalid(requestId,referenceId,"INVALID_IMAGE_TYPE");if(!consume(sessionId)){log.warn("[HYBRID][REJECTED] requestId={} reason=SESSION_REPLAYED",requestId);return invalid(requestId,referenceId,"SESSION_REPLAYED");}
 try{log.info("[HYBRID][ENGINE_START] requestId={} referenceId={} singleFrame=true",requestId,referenceId);var o=engine.verifySingleImage(requestId,image.getBytes(),referenceId);log.info("[HYBRID][ENGINE_RESULT] requestId={} result={} similarity={} quality={} liveness={} processingMs={} reasons={}",requestId,o.result(),o.similarity(),o.qualityScore(),o.livenessScore(),o.processingMs(),o.reasonCodes());return new HybridVerificationResponse(requestId,sessionId,referenceId,Status.valueOf(o.result()),o.similarity(),o.livenessScore(),o.qualityScore(),o.processingMs(),o.reasonCodes());}catch(IllegalArgumentException e){log.warn("[HYBRID][ENGINE_REJECTED] requestId={} reason={}",requestId,e.getMessage());return new HybridVerificationResponse(requestId,sessionId,referenceId,Status.INVALID_REQUEST,null,null,null,0,List.of(reason(e.getMessage())));}catch(Exception e){log.error("[HYBRID][ENGINE_ERROR] requestId={} referenceId={}",requestId,referenceId,e);return new HybridVerificationResponse(requestId,sessionId,referenceId,Status.PROCESSING_ERROR,null,null,null,0,List.of("MODEL_ERROR"));}}
 private boolean consume(String id){AtomicBoolean accepted=new AtomicBoolean(false);sessions.computeIfPresent(id,(k,s)->{if(s.consumed())return s;accepted.set(true);return new Session(s.sessionId(),s.referenceId(),s.expiresAt(),true);});return accepted.get();}
 private HybridVerificationResponse invalid(String requestId,String referenceId,String reason){log.info("[HYBRID][INVALID_REQUEST] requestId={} referenceId={} reason={}",requestId,referenceId,reason);return new HybridVerificationResponse(requestId,null,referenceId,Status.INVALID_REQUEST,null,null,null,0,List.of(reason));}
 private String reason(String v){return switch(v==null?"":v){case "INVALID_IMAGE","SUSPICIOUS_IMAGE_DIMENSIONS","IMAGE_TOO_LARGE","INVALID_IMAGE_TYPE","NO_FACE","MULTIPLE_FACES","FACE_TOO_SMALL","LOW_QUALITY","LIVENESS_FAILED","REFERENCE_NOT_FOUND","MODEL_ERROR","SIMILARITY_BELOW_THRESHOLD"->v;default->"INVALID_IMAGE";};}
 public enum Status{MATCH,NO_MATCH,INCONCLUSIVE,INVALID_REQUEST,PROCESSING_ERROR} public record SessionResponse(String sessionId,String referenceId,Instant expiresAt){} public record HybridVerificationResponse(String requestId,String sessionId,String referenceId,Status result,Double similarity,Double livenessScore,Double qualityScore,long processingTimeMs,List<String> reasonCodes){} private record Session(String sessionId,String referenceId,Instant expiresAt,boolean consumed){}
}